version: '3'

services:
  hugo:
    container_name: hugo
    image: peaceiris/hugo:v0.91.2
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts