[build]
  publish = "public"
  command = "hugo --minify --gc"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[build.environment]
  HUGO_VERSION = "0.91.2"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[context.production]
command = "hugo --minify --gc --baseUrl https://reflectoring.io"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify --gc --baseUrl ${DEPLOY_PRIME_URL}"

[context.deploy-preview.environment]
HUGO_ENV = "staging"

[[redirects]]
  from = "/feed.xml"
  to = "/index.xml"
  status = 301
  force = true

[[redirects]]
  from = "/e/book/"
  to = "/book"
  status = 301
  force = true

[[redirects]]
  from = "/get-your-hands-dirty-on-clean-architecture"
  to = "/book"
  status = 301
  force = true

[[redirects]]
  from = "/newsletters"
  to = "/simplify"
  status = 301
  force = true

[[redirects]]
  from = "/mailing-list"
  to = "/simplify"
  status = 301
  force = true

[[redirects]]
  from = "/review-clean-architecture"
  to = "/book-review-clean-architecture"
  status = 301
  force = true

[[redirects]]
  from = "/review-java-by-comparison"
  to = "/book-review-java-by-comparison"
  status = 301
  force = true

[[redirects]]
  from = "/review-your-code-as-a-crime-scene"
  to = "/book-review-your-code-as-a-crime-scene"
  status = 301
  force = true

[[redirects]]
  from = "/spring-boot-testcontainers"
  to = "/spring-boot-flyway-testcontainers"
  status = 301
  force = true

[[redirects]]
  from = "/spring-data-mvc-pagination"
  to = "/spring-boot-paging"
  status = 301
  force = true

[[redirects]]
  from = "/tracing-with-spring-cloud-sleuth"
  to = "/spring-boot-tracing"
  status = 301
  force = true

[[redirects]]
  from = "/write-for-me"
  to = "/contribute/become-an-author"
  status = 301
  force = true

[[redirects]]
  from = "/write-with-me"
  to = "/contribute/become-an-author"
  status = 301
  force = true

[[redirects]]
  from = "/2022-03-15-feature-flags-make-or-buy"
  to = "/feature-flags-make-or-buy"
  status = 301
  force = true

[[redirects]]
  from = "/javaland"
  to = "https://thombergs.gumroad.com/l/gyhdoca/javaland"
  status = 301
  force = true

